apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "primer.fullname" . }}-frontend
  labels:
    {{- include "primer.labels" . | nindent 4 }}
    {{- include "primer.frontend.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "primer.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "primer.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          env:
            - name: PRIMER_API_HOST
              value: {{ include "primer.fullname" . }}-server
            - name: PRIMER_API_PORT
              value: {{ .Values.server.port | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
