apiVersion: v1
kind: Secret
metadata:
  name: {{ include "primer.fullname" . }}
  labels:
    {{- include "primer.labels" . | nindent 4 }}
type: Opaque
stringData:
  PRIMER_ADMIN_API_KEY: {{ .Values.secrets.adminApiKey | quote }}
  PRIMER_JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  PRIMER_DATABASE_URL: {{ include "primer.databaseUrl" . | quote }}
