"""add session customization snapshots

Revision ID: 1c66d7ff642e
Revises: 44c9b01ccad2
Create Date: 2026-03-18 08:44:16.955725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c66d7ff642e"
down_revision: Union[str, None] = "44c9b01ccad2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_customizations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("customization_type", sa.String(length=30), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("provenance", sa.String(length=30), server_default="unknown", nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("source_path", sa.String(length=1024), nullable=True),
        sa.Column("invocation_count", sa.Integer(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_session_customizations_session_id",
        "session_customizations",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_session_customizations_session_id", table_name="session_customizations")
    op.drop_table("session_customizations")
    # ### end Alembic commands ###
