"""add session workflow profiles

Revision ID: 44c9b01ccad2
Revises: 0f3b0a1e2c91
Create Date: 2026-03-13 13:02:58.876348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44c9b01ccad2"
down_revision: Union[str, None] = "0f3b0a1e2c91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_workflow_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("fingerprint_id", sa.String(length=255), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("steps", sa.JSON(), nullable=True),
        sa.Column("archetype", sa.String(length=50), nullable=True),
        sa.Column("archetype_source", sa.String(length=20), nullable=True),
        sa.Column("archetype_reason", sa.Text(), nullable=True),
        sa.Column("top_tools", sa.JSON(), nullable=True),
        sa.Column("delegation_count", sa.Integer(), nullable=False),
        sa.Column("verification_run_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_session_workflow_profiles_session_id",
        "session_workflow_profiles",
        ["session_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_session_workflow_profiles_session_id", table_name="session_workflow_profiles")
    op.drop_table("session_workflow_profiles")
    # ### end Alembic commands ###
