"""add quality metrics tables

Revision ID: 7752efb0e9d2
Revises: 2d97113e257c
Create Date: 2026-02-15 18:33:00.238565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7752efb0e9d2"
down_revision: Union[str, None] = "2d97113e257c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "git_repositories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("github_id", sa.Integer(), nullable=True),
        sa.Column("default_branch", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_name"),
        sa.UniqueConstraint("github_id"),
    )
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=False),
        sa.Column("engineer_id", sa.String(length=36), nullable=True),
        sa.Column("github_pr_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("head_branch", sa.String(length=255), nullable=True),
        sa.Column("additions", sa.Integer(), nullable=False),
        sa.Column("deletions", sa.Integer(), nullable=False),
        sa.Column("changed_files", sa.Integer(), nullable=False),
        sa.Column("review_comments_count", sa.Integer(), nullable=False),
        sa.Column("commits_count", sa.Integer(), nullable=False),
        sa.Column("merged_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("pr_created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["engineer_id"],
            ["engineers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["git_repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "github_pr_number"),
    )
    op.create_table(
        "session_commits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=True),
        sa.Column("pull_request_id", sa.String(length=36), nullable=True),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("commit_message", sa.Text(), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("author_email", sa.String(length=255), nullable=True),
        sa.Column("committed_at", sa.DateTime(), nullable=True),
        sa.Column("files_changed", sa.Integer(), nullable=False),
        sa.Column("lines_added", sa.Integer(), nullable=False),
        sa.Column("lines_deleted", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"],
            ["pull_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["git_repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "commit_sha"),
    )
    with op.batch_alter_table("sessions") as batch_op:
        batch_op.add_column(sa.Column("repository_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_sessions_repository_id", "git_repositories", ["repository_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions") as batch_op:
        batch_op.drop_constraint("fk_sessions_repository_id", type_="foreignkey")
        batch_op.drop_column("repository_id")
    op.drop_table("session_commits")
    op.drop_table("pull_requests")
    op.drop_table("git_repositories")
    # ### end Alembic commands ###
