"""add data_summary to narrative_cache

Revision ID: 7dda515efd1d
Revises: 5ab15e4f648f
Create Date: 2026-02-19 11:50:06.908981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7dda515efd1d"
down_revision: Union[str, None] = "5ab15e4f648f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("narrative_cache", sa.Column("data_summary", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("narrative_cache", "data_summary")
    # ### end Alembic commands ###
