"""add repository context fields

Revision ID: d4f9d944e709
Revises: 5fc2e3115f6c
Create Date: 2026-03-11 10:08:25.451964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4f9d944e709"
down_revision: Union[str, None] = "5fc2e3115f6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "git_repositories", sa.Column("primary_language", sa.String(length=100), nullable=True)
    )
    op.add_column("git_repositories", sa.Column("language_breakdown", sa.JSON(), nullable=True))
    op.add_column("git_repositories", sa.Column("repo_size_kb", sa.Integer(), nullable=True))
    op.add_column("git_repositories", sa.Column("has_test_harness", sa.Boolean(), nullable=True))
    op.add_column("git_repositories", sa.Column("has_ci_pipeline", sa.Boolean(), nullable=True))
    op.add_column("git_repositories", sa.Column("test_maturity_score", sa.Float(), nullable=True))
    op.add_column(
        "git_repositories", sa.Column("repo_context_checked_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("git_repositories", "repo_context_checked_at")
    op.drop_column("git_repositories", "test_maturity_score")
    op.drop_column("git_repositories", "has_ci_pipeline")
    op.drop_column("git_repositories", "has_test_harness")
    op.drop_column("git_repositories", "repo_size_kb")
    op.drop_column("git_repositories", "language_breakdown")
    op.drop_column("git_repositories", "primary_language")
    # ### end Alembic commands ###
