"""add memory tables

Revision ID: ed2b38b8d95a
Revises: 9c4e71d3b2a1
Create Date: 2026-06-07 13:11:24.075361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed2b38b8d95a"
down_revision: Union[str, None] = "9c4e71d3b2a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_scopes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), server_default="project", nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=True),
        sa.Column("last_consolidation_at", sa.DateTime(), nullable=True),
        sa.Column("memory_paused_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["git_repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id"),
    )
    op.create_table(
        "memory_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("concepts", sa.JSON(), nullable=True),
        sa.Column("files", sa.JSON(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="sketch", nullable=False),
        sa.Column("confidence_score", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("corroboration_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("judge_critique", sa.Text(), nullable=True),
        sa.Column(
            "origin", sa.String(length=30), server_default="passive_extraction", nullable=False
        ),
        sa.Column("created_by_engineer_id", sa.String(length=36), nullable=True),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("activation_baseline", sa.JSON(), nullable=True),
        sa.Column("activation_observation", sa.JSON(), nullable=True),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.Column("token_cost", sa.JSON(), nullable=True),
        sa.Column("efficiency_estimate", sa.JSON(), nullable=True),
        sa.Column("export_status", sa.String(length=20), server_default="none", nullable=False),
        sa.Column("export_pr_number", sa.Integer(), nullable=True),
        sa.Column("export_cooldown_until", sa.DateTime(), nullable=True),
        sa.Column("superseded_by_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_engineer_id"],
            ["engineers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["memory_scopes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["memory_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "content_hash", name="uq_memory_entry_scope_hash"),
    )
    op.create_index(
        "ix_memory_entries_scope_status", "memory_entries", ["scope_id", "status"], unique=False
    )
    op.create_table(
        "memory_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("event_kind", sa.String(length=40), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memory_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memory_events_memory_time", "memory_events", ["memory_id", "occurred_at"], unique=False
    )
    op.create_table(
        "memory_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_kind", sa.String(length=30), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("engineer_id", sa.String(length=36), nullable=True),
        sa.Column("independent", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["engineer_id"],
            ["engineers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memory_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memory_evidence_memory_independent",
        "memory_evidence",
        ["memory_id", "independent"],
        unique=False,
    )
    op.create_index(
        "ix_memory_evidence_session_kind",
        "memory_evidence",
        ["session_id", "evidence_kind"],
        unique=False,
    )
    op.create_table(
        "memory_injections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("engineer_id", sa.String(length=36), nullable=False),
        sa.Column("surface", sa.String(length=20), nullable=False),
        sa.Column("token_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "injected_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["engineer_id"],
            ["engineers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memory_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memory_injections_engineer_time",
        "memory_injections",
        ["engineer_id", "injected_at"],
        unique=False,
    )
    op.create_index(
        "ix_memory_injections_memory_time",
        "memory_injections",
        ["memory_id", "injected_at"],
        unique=False,
    )
    op.create_index(
        "ix_memory_injections_session", "memory_injections", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_memory_injections_session", table_name="memory_injections")
    op.drop_index("ix_memory_injections_memory_time", table_name="memory_injections")
    op.drop_index("ix_memory_injections_engineer_time", table_name="memory_injections")
    op.drop_table("memory_injections")
    op.drop_index("ix_memory_evidence_session_kind", table_name="memory_evidence")
    op.drop_index("ix_memory_evidence_memory_independent", table_name="memory_evidence")
    op.drop_table("memory_evidence")
    op.drop_index("ix_memory_events_memory_time", table_name="memory_events")
    op.drop_table("memory_events")
    op.drop_index("ix_memory_entries_scope_status", table_name="memory_entries")
    op.drop_table("memory_entries")
    op.drop_table("memory_scopes")
    # ### end Alembic commands ###
